import type { Metadata } from "next";

import "./globals.css";
import { Layout } from "antd"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import HeaderLayout from "./ui/Header";


export const metadata: Metadata = {
  title: "Akira MMD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Layout>
            <HeaderLayout />
            <Layout>
              {children}
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
